// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// ── Interfaces ────────────────────────────────────────────────────────────────

/// @dev Minimal interface for the EZKL-generated Halo2 KZG verifier.
///      The full verifier ABI is generated by EZKL — we only need verifyProof.
interface IHalo2Verifier {
    function verifyProof(
        bytes calldata proof,
        uint256[] calldata publicInputs
    ) external view returns (bool);
}

/// @dev StarkNet core messaging contract (same address on all EVM networks).
///      https://docs.starknet.io/documentation/architecture_and_concepts/L1-L2_Communication/messaging-mechanism/
interface IStarknetMessaging {
    function sendMessageToL2(
        uint256 toAddress,
        uint256 selector,
        uint256[] calldata payload
    ) external payable returns (bytes32, uint256);
}

// ── InferenceBridge ───────────────────────────────────────────────────────────

/// @title  InferenceBridge
/// @notice Verifies an EZKL Halo2 proof via the deployed Halo2Verifier, then
///         relays the result to InferenceVerifier.cairo on StarkNet via the
///         canonical L1→L2 messaging contract.
///
/// @dev    Only used when settlementChain = 'starknet'. For eth-sepolia and
///         base-sepolia settlement the gateway calls Halo2Verifier directly.
///
/// Deployment:
///   - Deploy one instance on Eth Sepolia (used as the default EVM source for
///     StarkNet settlement).
///   - Set halo2Verifier  = deployed Halo2Verifier.sol address
///   - Set starknetCore   = StarkNet messaging contract address for this network
///   - Set cairoDest      = InferenceVerifier.cairo contract address (felt252)
///   - Set cairoSelector  = pedersen/keccak selector for consume_inference_result
contract InferenceBridge {

    // ── Events ────────────────────────────────────────────────────────────────

    /// @notice Emitted when a proof passes KZG verification.
    event InferenceVerified(
        bytes32 indexed inferenceId,
        address indexed submitter,
        bytes32           modelHash,
        uint256           timestamp
    );

    /// @notice Emitted when the L1→L2 message is dispatched to StarkNet core.
    event MessageSentToStarkNet(
        bytes32 indexed inferenceId,
        bytes32         msgHash,
        uint256         nonce
    );

    // ── State ─────────────────────────────────────────────────────────────────

    address public immutable owner;
    IHalo2Verifier    public immutable halo2Verifier;
    IStarknetMessaging public immutable starknetCore;

    /// @dev InferenceVerifier.cairo contract address as uint256 (felt252).
    uint256 public immutable cairoDest;

    /// @dev keccak256("consume_inference_result") truncated to felt252.
    ///      Compute off-chain:
    ///        python3 -c "from starkware.cairo.lang.compiler.identifier_definition import *;
    ///                     from starkware.crypto.signature.fast_pedersen_hash import pedersen_hash;
    ///                     print(hex(get_selector_from_name('consume_inference_result')))"
    uint256 public immutable cairoSelector;

    /// @dev Prevents replaying the same inferenceId twice.
    mapping(bytes32 => bool) public verified;

    // ── Constructor ───────────────────────────────────────────────────────────

    constructor(
        address _halo2Verifier,
        address _starknetCore,
        uint256 _cairoDest,
        uint256 _cairoSelector
    ) {
        owner           = msg.sender;
        halo2Verifier   = IHalo2Verifier(_halo2Verifier);
        starknetCore    = IStarknetMessaging(_starknetCore);
        cairoDest       = _cairoDest;
        cairoSelector   = _cairoSelector;
    }

    // ── Core: verify + bridge ─────────────────────────────────────────────────

    /// @notice Verify an EZKL Halo2 proof and relay the result to StarkNet.
    ///
    /// @param proof        Raw proof bytes from EZKL.
    /// @param publicInputs Public inputs array (model output, input hash, etc).
    /// @param inferenceId  Unique job identifier — keccak256(jobId) from gateway.
    /// @param modelHash    keccak256(modelName + modelVersion) — must match
    ///                     what the contract was compiled against.
    ///
    /// @dev   msg.value is forwarded to StarkNet core as the L1→L2 fee.
    ///        Caller must pass enough ETH to cover the messaging fee
    ///        (query estimateMessageFee() on StarkNet core first).
    function verifyAndBridge(
        bytes   calldata proof,
        uint256[] calldata publicInputs,
        bytes32 inferenceId,
        bytes32 modelHash
    ) external payable {
        // ── 1. Replay protection ──────────────────────────────────────────────
        require(!verified[inferenceId], "InferenceBridge: already verified");
        verified[inferenceId] = true;

        // ── 2. KZG pairing check ──────────────────────────────────────────────
        bool ok = halo2Verifier.verifyProof(proof, publicInputs);
        require(ok, "InferenceBridge: proof verification failed");

        uint256 ts = block.timestamp;

        emit InferenceVerified(inferenceId, msg.sender, modelHash, ts);

        // ── 3. Build L1→L2 payload ────────────────────────────────────────────
        // Payload layout matches consume_inference_result(ref self, from_address,
        //   inference_id, model_hash, timestamp, submitter)
        // from_address is injected by StarkNet core automatically — not in payload.
        uint256[] memory payload = new uint256[](4);
        payload[0] = uint256(inferenceId);              // inference_id  (felt252)
        payload[1] = uint256(modelHash);                // model_hash    (felt252)
        payload[2] = ts;                                // timestamp     (u64)
        payload[3] = uint256(uint160(msg.sender));      // submitter     (EthAddress)

        // ── 4. Send to StarkNet core ──────────────────────────────────────────
        (bytes32 msgHash, uint256 nonce) = starknetCore.sendMessageToL2{value: msg.value}(
            cairoDest,
            cairoSelector,
            payload
        );

        emit MessageSentToStarkNet(inferenceId, msgHash, nonce);
    }

    // ── View helpers ──────────────────────────────────────────────────────────

    /// @notice Returns true if this inferenceId has already been bridged.
    function isVerified(bytes32 inferenceId) external view returns (bool) {
        return verified[inferenceId];
    }

    // ── Admin ─────────────────────────────────────────────────────────────────

    /// @dev Allow owner to rescue any ETH accidentally sent to this contract.
    function withdraw() external {
        require(msg.sender == owner, "InferenceBridge: not owner");
        payable(owner).transfer(address(this).balance);
    }

    receive() external payable {}
}
